import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'registry': 'src/registry.ts',
    'observe/index': 'src/observe/index.ts',
    'ingest/index': 'src/ingest/index.ts',
    'testing/index': 'src/testing/index.ts',
    'providers/claude/index': 'src/providers/claude/index.ts',
    'providers/codex/index': 'src/providers/codex/index.ts',
    'providers/cursor/index': 'src/providers/cursor/index.ts',
    'providers/opencode/index': 'src/providers/opencode/index.ts',
    'providers/pi/index': 'src/providers/pi/index.ts',
    'providers/acp/index': 'src/providers/acp/index.ts',
    'providers/antigravity/index': 'src/providers/antigravity/index.ts',
    'providers/grok/index': 'src/providers/grok/index.ts',
    'providers/kimi/index': 'src/providers/kimi/index.ts',
    'providers/oar/index': 'src/providers/oar/index.ts',
    'providers/morph/index': 'src/providers/morph/index.ts',
    'providers/copilot/index': 'src/providers/copilot/index.ts',
    'providers/openclaw/index': 'src/providers/openclaw/index.ts',
    'providers/qwen/index': 'src/providers/qwen/index.ts',
    'providers/droid/index': 'src/providers/droid/index.ts',
    'providers/deepseek/index': 'src/providers/deepseek/index.ts',
    'providers/cline/index': 'src/providers/cline/index.ts',
    'providers/fx/index': 'src/providers/fx/index.ts',
    'providers/devin/index': 'src/providers/devin/index.ts',
    'providers/hermes/index': 'src/providers/hermes/index.ts',
  },
  format: 'esm',
  fixedExtension: false,
  platform: 'node',
  target: 'node22.18',
  dts: true,
  clean: true,
  deps: { onlyBundle: [], onlyImport: ['fzstd', 'xxhashjs', '@bufbuild/protobuf', 'picomatch'] },
})
